export const NATS_SERVICE = 'NATS_SERVICE';
export const EMAILS_SERVICE = 'EMAILS_SERVICE';
export const SERVICE_NAME = 'reservations-service';
export const ADMIN_SUBSCRIPTIONS_SERVICE = 'ADMIN_SUBSCRIPTIONS_SERVICE';
export const SUBSCRIBERS_SERVICE = 'SUBSCRIBERS_SERVICE';
